sudo: required

group: deprecated-2017Q2

language: python

branches:
  only:
  - master

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq

addons:
  postgresql: "9.6"

virtualenv:
  system_site_packages: true

env:
  global:
    - AUTH_DISABLED=1
    - LAUNCH_BY_NAME_indexer_inception=1
    - LAUNCH_BY_NAME_retriever_inception=1
    - LAUNCH_BY_NAME_detector_coco=1
    - LAUNCH_Q_qclusterer=1

before_install:
  - sudo apt-get -qq update
  - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz && tar xvfJ ffmpeg-release-64bit-static.tar.xz
  - sudp mv ffmpeg*/* /bin/
  - sudo apt-get -qq install -y pkg-config python-dev unzip swig3.0 libopencv-dev libhdf5-dev python-pip libav-tools libjpeg-dev  libpng-dev  libtiff-dev  libjasper-dev  python-numpy python-scipy  python-pycurl  python-opencv
  - sudo dpkg -L python-opencv
  - sudo wget --quiet https://yt-dl.org/downloads/latest/youtube-dl -O /bin/youtube-dl
  - sudo chmod a+rx /bin/youtube-dl
  - youtube-dl -U
  - pip install -q --only-binary=numpy,scipy numpy scipy
  - pip install -q https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.0-cp27-none-linux_x86_64.whl
  - pip install -q --no-deps keras
  - pip install -q --no-deps h5py
  - pip install -q --no-cache-dir http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp27-none-linux_x86_64.whl
  - pip install -q torchvision
install: "pip install -q -r requirements.txt > /dev/null"


before_script:
  - cd repos/lopq/python && python setup.py install && cd ../../..
  - python manage.py migrate
  - python manage.py runserver 8000 &
  - cd tests && wget --quiet https://www.dropbox.com/s/xwbk5g1qit5s9em/WorldIsNotEnough.mp4 && cd ..
  - cd dvalib/crfasrnn/cpp && ./compile.sh && cd ../../..
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - fab init_fs
  - fab init_server
  - fab init_models
  - fab ci
  - fab ci_face
  - fab ci_search
  - wget --quiet localhost:8000
  - wget --quiet localhost:8000/videos/
  - wget --quiet localhost:8000/videos/1/
  - wget --quiet localhost:8000/status
  - wget --quiet localhost:8000/queries/
  - wget --quiet localhost:8000/queries/1/
  - wget --quiet localhost:8000/tasks/
  - wget --quiet localhost:8000/retrievers/
  - wget --quiet localhost:8000/textsearch/
  - wget --quiet localhost:8000/models/
  - wget --quiet localhost:8000/status
  - wget --quiet localhost:8000/api/users/
  - wget --quiet localhost:8000/api/videos/
  - wget --quiet localhost:8000/api/tubes/
  - wget --quiet localhost:8000/api/frames/
  - wget --quiet localhost:8000/api/framelabels/
  - wget --quiet localhost:8000/api/regionlabels/
  - wget --quiet localhost:8000/api/segmentlabels/
  - wget --quiet localhost:8000/api/tubelabels/
  - wget --quiet localhost:8000/api/videolabels/
  - wget --quiet localhost:8000/api/labels/
  - wget --quiet localhost:8000/api/segments/
  - wget --quiet localhost:8000/api/regions/
  - wget --quiet localhost:8000/api/queries/
  - wget --quiet localhost:8000/api/queryresults/
  - wget --quiet localhost:8000/api/indexentries/
  - wget --quiet localhost:8000/api/events/