 version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     build: .
     image: aub3dva:gpu
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
     command: bash -c "git pull && fab start_server_container:1"
     ports:
       - "8000:8000"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:

