apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: postgres
    tier: backend
    role: master
spec:
  selector:
    app: postgres
    tier: backend
    role: master
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresdata-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: slow
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres-master
spec:
  replicas: 1
  serviceName: "postgres-master"
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - image: postgres:9.6-alpine
        resources:
          requests:
            memory: "2000Mi"
            cpu: "2"
          limits:
            memory: "4000Mi"
            cpu: "4"
        imagePullPolicy: "IfNotPresent"
        name: master
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbusername
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbpassword
        ports:
        - containerPort: 5432
          name: postgres-master
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresdata-claim
