# specify using docker-compose -f docker-compose-deploy.yml up
 version: '3'
 services:
   db:
     image: postgres:9.6.6
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     env_file:
       - ../common.env
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     env_file:
       - ../common.env
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   redis:
     image: bitnami/redis:latest
     container_name: dva-redis
     env_file:
       - ../common.env
     volumes:
       - dvaredis:/bitnami
   dva:
     image: akshayubhat/dva-auto:latest
     container_name: webserver
     env_file:
       - ../common.env
     environment:
       - LAUNCH_NOTEBOOK=1
       - LAUNCH_SERVER_NGINX=1
       - LAUNCH_SCHEDULER=1
       - INIT_PROCESS=/root/DVA/configs/custom_defaults/init_process.json
     command: bash -c "git pull && sleep 10 && ./start_container.py"
     ports:
       - "127.0.0.1:8000:80" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
       - "127.0.0.1:8888:8888" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
     depends_on:
       - db
       - rabbit
       - redis
     volumes:
       - dvadata:/root/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:
  dvaredis:
