# specify using docker-compose -f docker-compose-deploy.yml up
 version: '3'
 services:
   db:
     image: postgres:9.6.6
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=pgdbuser
       - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     image: akshayubhat/dva-auto:latest
     container_name: webserver
     env_file:
       - ./common.env
     environment:
       - LAUNCH_SERVER_NGINX=1
       - LAUNCH_Q_GLOBAL_MODEL=1
       - LAUNCH_Q_GLOBAL_RETRIEVER=1
       - LAUNCH_BY_NAME_indexer_inception=1
       - LAUNCH_BY_NAME_indexer_facenet=1
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_BY_NAME_detector_coco=1
       - LAUNCH_BY_NAME_analyzer_crnn=1
       - LAUNCH_BY_NAME_analyzer_tagger=1
       - LAUNCH_BY_NAME_detector_face=1
       - LAUNCH_BY_NAME_detector_textbox=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_SCHEDULER=1
       - INIT_PROCESS=/root/DVA/configs/custom_defaults/init_process.json
     command: bash -c "git pull && sleep 10 && ./start_container.py"
     ports:
       - "127.0.0.1:8000:80" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
       - "127.0.0.1:8888:8888" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:
