# specify using docker-compose -f docker-compose-deploy.yml up
 version: '3'
 services:
   db:
     image: postgres:9.6.6
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     env_file:
       - ./common_non_nfs.env
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     env_file:
       - ./common_non_nfs.env
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   webserver:
     image: akshayubhat/dva-auto:latest
     container_name: webserver
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_SERVER_NGINX=1
       - INIT_PROCESS=/root/DVA/configs/custom_defaults/init_process.json
     command: bash -c "git pull && sleep 10 && ./start_container.py"
     ports:
       - "127.0.0.1:8000:80" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
       - "127.0.0.1:8888:8888" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
     depends_on:
       - db
       - rabbit
   extractor:
     image: akshayubhat/dva-auto:latest
     container_name: extractor
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_Q_qextract=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   scheduler:
     image: akshayubhat/dva-auto:latest
     container_name: scheduler
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_SCHEDULER=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   inception:
     image: akshayubhat/dva-auto:latest
     container_name: inception
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_indexer_inception=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   facenet:
     image: akshayubhat/dva-auto:latest
     container_name: facenet
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_indexer_facenet=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   coco:
     image: akshayubhat/dva-auto:latest
     container_name: coco
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_detector_coco=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   crnn:
     image: akshayubhat/dva-auto:latest
     container_name: crnn
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_analyzer_crnn=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   tagger:
     image: akshayubhat/dva-auto:latest
     container_name: tagger
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_analyzer_tagger=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   face:
     image: akshayubhat/dva-auto:latest
     container_name: face
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_detector_face=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   textdetector:
     image: akshayubhat/dva-auto:latest
     container_name: textdetector
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_BY_NAME_detector_textbox=1
     command: bash -c "sleep 60 && git pull && ./start_container.py"
     depends_on:
       - db
       - rabbit
   global_model:
     image: akshayubhat/dva-auto:latest
     container_name: global_model
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_Q_GLOBAL_MODEL=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
   global_retriever:
     image: akshayubhat/dva-auto:latest
     container_name: global_retriever
     env_file:
       - ./common_non_nfs.env
       - ~/aws.env
     environment:
       - LAUNCH_Q_GLOBAL_RETRIEVER=1
     command: bash -c "git pull && sleep 60 && ./start_container.py"
     depends_on:
       - db
       - rabbit
 volumes:
  dvapgdata:
  dvarabbit: