# specify using docker-compose -f docker-compose-deploy.yml up
 version: '3'
 services:
   dva:
     image: akshayubhat/dva-auto:gpu
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - LAUNCH_SERVER_NGINX=1
       - DISABLE_DEBUG=1
       - BROKER_URL=${BROKER_URL}
       - DATABASE_URL=${DATABASE_URL}
       - SECRET_KEY=${SECRET_KEY}
       - LAUNCH_Q_qindexer=1
       - LAUNCH_Q_qretriever=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_Q_qdetector=1
       - LAUNCH_Q_qfaceretriever=1
       - LAUNCH_Q_qclusterer=1
       - LAUNCH_Q_qfacedetector=1
       - LAUNCH_Q_qtrainer=1
       - CELERY_MUTE=1
       - MEDIA_BUCKET=${MEDIA_BUCKET}
       - GPU_AVAILABLE=1
       - DVA_PRIVATE_ENABLE=1
     command: bash -c "youtube-dl -U && git pull && fab pull_private && fab start_container_server"
     ports:
       - "127.0.0.1:8500:80"
     volumes:
       - dvadata:/root/DVA/dva/media
   dva-ocr:
     image: akshayubhat/dva-auto:caffe
     container_name: dva-ocr
     environment:
       - GPU_AVAILABLE=1
       - DOCKER_MODE=true
       - BROKER_URL=${BROKER_URL}
       - DATABASE_URL=${DATABASE_URL}
       - SECRET_KEY=${SECRET_KEY}
       - MEDIA_BUCKET=${MEDIA_BUCKET}
       - CELERY_MUTE=1
       - DVA_PRIVATE_ENABLE=1
       - LAUNCH_Q_qocr=1
       - CAFFE_MODE=1
     command: bash -c "sleep 60 && git pull && fab pull_private && fab start_container_worker"
     volumes:
       - dvadata:/root/DVA/dva/media
   dva-crnn:
     image: akshayubhat/dva-auto:gpu
     container_name: dva-crnn
     environment:
       - GPU_AVAILABLE=1
       - DOCKER_MODE=true
       - BROKER_URL=${BROKER_URL}
       - DATABASE_URL=${DATABASE_URL}
       - SECRET_KEY=${SECRET_KEY}
       - MEDIA_BUCKET=${MEDIA_BUCKET}
       - CELERY_MUTE=1
       - DVA_PRIVATE_ENABLE=1
       - LAUNCH_Q_qcrnn=1
       - PYTORCH_MODE=1
     command: bash -c "sleep 60 && git pull && fab pull_private && fab start_container_worker"
     volumes:
       - dvadata:/root/DVA/dva/media
 volumes:
  dvadata:
    external: true