# specify using docker-compose -f docker-compose-deploy.yml up
 version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=pgdbuser
       - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     image: akshayubhat/dva-auto:latest
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - LAUNCH_SERVER_NGINX=1
       - DISABLE_DEBUG=1
       - SECRET_KEY=283y312bhv2b13v13
       - LAUNCH_Q_qindexer=1
       - LAUNCH_Q_qretriever=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_Q_qdetector=1
       - LAUNCH_Q_qfaceretriever=1
       - LAUNCH_Q_qclusterer=1
       - LAUNCH_Q_qfacedetector=1
     command: bash -c "youtube-dl -U && git pull && fab start_container"
     ports:
       - "127.0.0.1:8000:80" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
 volumes:
  dvapgdata:
  dvadata:
    external: true
  dvarabbit:
