
 version: '3'
 services:
   db:
     image: postgres:9.6.6
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     env_file:
       - ../common.env
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     env_file:
       - ../common.env
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   redis:
     image: bitnami/redis:latest
     container_name: dva-redis
     env_file:
       - ../common.env
     volumes:
       - dvaredis:/bitnami       
   webserver:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - LAUNCH_SERVER_NGINX=1
       - LAUNCH_NOTEBOOK=1
       - INIT_PROCESS=/root/DVA/configs/custom_defaults/init_process.json
     command: bash -c "git pull && sleep 10 && ./start_container.py"
     ports:
       - "127.0.0.1:8000:80"
       - "127.0.0.1:8888:8888"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   non-gpu-workers:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_SCHEDULER=1
       - LAUNCH_Q_GLOBAL_RETRIEVER=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   inception:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=0
       - GPU_MEMORY=0.3
       - LAUNCH_BY_NAME_indexer_inception=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   crnn:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=0
       - GPU_MEMORY=0.3
       - LAUNCH_BY_NAME_analyzer_crnn=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   coco:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=1
       - GPU_MEMORY=0.5
       - LAUNCH_BY_NAME_detector_coco=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   textbox:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=1
       - GPU_MEMORY=0.5
       - LAUNCH_BY_NAME_detector_textbox=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   face:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=2
       - GPU_MEMORY=0.6
       - LAUNCH_BY_NAME_detector_face=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   facenet:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=2
       - GPU_MEMORY=0.25
       - LAUNCH_BY_NAME_indexer_facenet=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   tagger:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1
       - NVIDIA_VISIBLE_DEVICES=2
       - GPU_MEMORY=0.25
       - LAUNCH_BY_NAME_analyzer_tagger=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
   global-model:
     image: akshayubhat/dva-auto:gpu
     env_file:
       - ../common.env
     environment:
       - GPU_AVAILABLE=1     
       - NVIDIA_VISIBLE_DEVICES=0
       - GPU_MEMORY=0.3
       - LAUNCH_Q_GLOBAL_MODEL=1
     command: bash -c "git pull && sleep 45 && ./start_container.py"
     depends_on:
       - db
       - redis       
       - rabbit
     volumes:
       - dvadata:/root/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:
  dvaredis:
